[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'simeji/winresizer'
